### ISSUE TITLE
StringIndexOutOfBoundsException when cut/copy

### ISSUE THREAD

**Issue by rocket-pig** [massivemadness/Squircle-CE#158]
**App Version:**
2022.2.1 (10013)

**Affected Device(s):**
Samsung A037_su with Android 12

**Describe the bug**
Its relatively minor and avoidable, as it only happens if you use keyboard keys (hold shift + move arrows) AND move UPwards.  Doing the same but moving down in the file as you select: when you hit Ctrl-C: no problems.

**To Reproduce**
1.  select text, moving from low to high
2.  copy or cut
3.  immediate window close, no auto-save happens.

**Stack trace I got from logcat**

FATAL EXCEPTION: main
Process: com.blacksquircle.ui, PID: 7249
java.lang.StringIndexOutOfBoundsException
	at android.text.SpannableStringBuilder.<init>(SpannableStringBuilder.java:64)
	at androidx.emoji2.text.SpannableBuilder.<init>(SpannableBuilder.java:86)
	at androidx.emoji2.text.SpannableBuilder.subSequence(SpannableBuilder.java:125)
	at com.blacksquircle.ui.editorkit.ExtensionsKt.getSelectedText(Extensions.kt:29)
	at com.blacksquircle.ui.editorkit.ExtensionsKt.cut(Extensions.kt:37)
	at com.blacksquircle.ui.feature.editor.ui.fragment.EditorFragment.onCutButton(EditorFragment.kt:522)
	at com.blacksquircle.ui.feature.editor.ui.fragment.EditorFragment$observeViewModel$8$pluginSupplier$1$4.invoke$lambda-0(EditorFragment.kt:302)
	at com.blacksquircle.ui.feature.editor.ui.fragment.EditorFragment$observeViewModel$8$pluginSupplier$1$4.$r8$lambda$K7_57HbTZi17QI2z9RQVsedwYj0(Unknown Source:0)
	at com.blacksquircle.ui.feature.editor.ui.fragment.EditorFragment$observeViewModel$8$pluginSupplier$1$4$$ExternalSyntheticLambda0.onShortcut(Unknown Source:2)
	at com.blacksquircle.ui.editorkit.plugin.shortcuts.ShortcutsPlugin.onKeyDown(ShortcutsPlugin.kt:50)
	at com.blacksquircle.ui.editorkit.widget.TextProcessor.onKeyDown(TextProcessor.kt:128)
	at android.view.KeyEvent.dispatch(KeyEvent.java:3664)
	at android.view.View.dispatchKeyEvent(View.java:14927)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1991)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1991)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1991)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1991)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1991)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1991)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1991)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1991)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1991)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1991)
	at com.android.internal.policy.DecorView.superDispatchKeyEvent(DecorView.java:1004)
	at com.android.internal.policy.PhoneWindow.superDispatchKeyEvent(PhoneWindow.java:1952)
	at android.app.Activity.dispatchKeyEvent(Activity.java:4225)
	at androidx.core.app.ComponentActivity.superDispatchKeyEvent(ComponentActivity.java:126)
	at androidx.core.view.KeyEventDispatcher.dispatchKeyEvent(KeyEventDispatcher.java:86)
	at androidx.core.app.ComponentActivity.dispatchKeyEvent(ComponentActivity.java:144)
	at androidx.appcompat.app.AppCompatActivity.dispatchKeyEvent(AppCompatActivity.java:601)
	at androidx.appcompat.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:60)
	at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.dispatchKeyEvent(AppCompatDelegateImpl.java:3106)
	at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:823)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:7722)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:7545)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6922)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6979)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6945)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:7143)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6953)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:7200)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6926)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6979)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6945)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6953)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6926)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6979)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6945)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:7176)
	at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:7363)
	at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:3411)
	at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:2972)
	at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:2963)
	at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:3388)
	at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:154)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:335)
	at android.os.Looper.loopOnce(Looper.java:186)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8669)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)

**Comment by massivemadness** [comment]
Fixed in [v2023.1.0](https://github.com/massivemadness/Squircle-CE/releases/tag/2023.1.0)
